fail_fast: true
repos:

  ################################################################################
  # Standard Hygiene Hooks
  ################################################################################
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: mixed-line-ending
        args: ["--fix=lf"]

  ################################################################################
  # Ruff: Linter and Formatter
  ################################################################################
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        name: Running ruff linter
        args: ["--fix"]
      - id: ruff-format
        name: Running ruff formatter

  ################################################################################
  # Static Analysis & Type Checking
  ################################################################################
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports", "raindropiopy"]
        pass_filenames: false
        additional_dependencies:
          - pydantic>=1.10.4,<3.0
          - types-requests
          - types-urllib3

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  ################################################################################
  # Confirm we don't have unused code:
  ################################################################################
  - repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.14'
    hooks:
      - id: vulture

  ################################################################################
  # Dependency Management
  ################################################################################
  - repo: https://github.com/tweag/FawltyDeps
    rev: v0.17.0
    hooks:
      - id: check-undeclared
      - id: check-unused
